import Foundation

struct SkiLengthRange {
    let minCm: Int
    let maxCm: Int

    var displayRange: String {
        if minCm == maxCm {
            return "\(minCm) cm"
        }
        return "\(minCm)–\(maxCm) cm"
    }
}

struct DINResult {
    let value: Double
    let code: String
    let skierType: String
    let isJuniorAdjusted: Bool
    let warnings: [String]

    var displayValue: String {
        if value == value.rounded() {
            return String(format: "%.1f", value)
        }
        return String(format: "%.2f", value).replacingOccurrences(of: "0$", with: "", options: .regularExpression)
    }

    var formattedValue: String {
        String(format: "%.2f", value)
    }

    var isHighForJunior: Bool {
        value > 6.0
    }
}

struct PoleRecommendation {
    let lengthCm: Int
    let type: PoleType

    enum PoleType {
        case alpine, xcClassic, xcSkate
        var label: String {
            switch self {
            case .alpine: return "Alpine Poles"
            case .xcClassic: return "XC Classic Poles"
            case .xcSkate: return "XC Skate Poles"
            }
        }
    }
}

enum BootSizeConfidence: String {
    case measured = "Based on foot measurement"
    case fromShoeSize = "Estimated from shoe size"
    case fromHeight = "Roughly estimated from height"
    case hasBoots = "From your boot's BSL"
}

struct BootSizeRecommendation {
    let measuredFootLengthMm: Int
    let recommendedMondoMm: Int
    let growthRoomMm: Int
    let euSize: String
    let estimatedBSL: Int
    let confidence: BootSizeConfidence

    var recommendedMondoCm: String {
        String(format: "%.1f", Double(recommendedMondoMm) / 10.0)
    }

    var measuredFootCm: String {
        String(format: "%.1f", Double(measuredFootLengthMm) / 10.0)
    }

    var growthRoomCm: String {
        String(format: "%.1f", Double(growthRoomMm) / 10.0)
    }
}

struct SkiRecommendation {
    let child: ChildSnapshot
    let alpineSkiLength: SkiLengthRange?
    let dinResult: DINResult?
    let xcClassicLength: SkiLengthRange?
    let xcSkateLength: SkiLengthRange?
    let alpinePoleLength: Int?
    let xcClassicPoleLength: Int?
    let xcSkatePoleLength: Int?
    let bootSizeRecommendation: BootSizeRecommendation
    let warnings: [String]
    let calculatedAt: Date

    struct ChildSnapshot {
        let name: String
        let heightCm: Int
        let weightKg: Int
        let age: Int
        let abilityLevel: AbilityLevel
        let skiTypes: [SkiType]
    }

    var shareText: String {
        var lines: [String] = []
        let name = child.name.isEmpty ? "Child" : child.name
        lines.append("\(name) — Ski Equipment Sizing")
        lines.append("Height: \(child.heightCm) cm | Weight: \(child.weightKg) kg | Age: \(child.age)")
        lines.append("Ability: \(child.abilityLevel.rawValue)")
        lines.append("")

        if let alpine = alpineSkiLength {
            lines.append("⛷ Alpine Ski Length: \(alpine.displayRange)")
        }
        if let din = dinResult {
            lines.append("🔧 DIN Setting: \(din.formattedValue) (Code \(din.code), \(din.skierType))")
            if din.isJuniorAdjusted {
                lines.append("   Junior safety adjustment applied")
            }
        }
        if let classic = xcClassicLength {
            lines.append("🎿 XC Classic Ski Length: \(classic.displayRange)")
        }
        if let skate = xcSkateLength {
            lines.append("🎿 XC Skate Ski Length: \(skate.displayRange)")
        }
        if let pole = alpinePoleLength {
            lines.append("📏 Alpine Poles: \(pole) cm")
        }
        if let pole = xcClassicPoleLength {
            lines.append("📏 XC Classic Poles: \(pole) cm")
        }
        if let pole = xcSkatePoleLength {
            lines.append("📏 XC Skate Poles: \(pole) cm")
        }
        let boot = bootSizeRecommendation
        if boot.confidence != .hasBoots {
            lines.append("👢 Boot Size: Mondo \(boot.recommendedMondoCm) (EU \(boot.euSize))")
        }
        lines.append("👢 BSL: \(boot.estimatedBSL) mm (\(boot.confidence.rawValue))")

        lines.append("")
        if dinResult != nil {
            lines.append("⚠️ DIN settings must be verified by a certified ski technician.")
            lines.append("")
        }
        lines.append("Generated by SkiKids app")

        return lines.joined(separator: "\n")
    }
}
