import { SkiRecommendation } from '../models/types';

function formatRange(minCm: number, maxCm: number): string {
  if (minCm === maxCm) return `${minCm} cm`;
  return `${minCm}\u2013${maxCm} cm`;
}

export function generateShareText(rec: SkiRecommendation): string {
  const lines: string[] = [];
  const name = rec.childName.trim() || 'Child';

  lines.push(`${name} \u2014 Ski Equipment Sizing`);
  lines.push(`Height: ${rec.heightCm} cm | Weight: ${rec.weightKg} kg | Age: ${rec.age}`);
  lines.push(`Ability: ${rec.abilityLevel}`);
  lines.push('');

  if (rec.alpineSkiLength) {
    lines.push(`\u26f7 Alpine Ski Length: ${formatRange(rec.alpineSkiLength.minCm, rec.alpineSkiLength.maxCm)}`);
  }
  if (rec.dinResult) {
    const dinValue = rec.dinResult.value.toFixed(2);
    lines.push(`\uD83D\uDD27 DIN Setting: ${dinValue} (Code ${rec.dinResult.code}, ${rec.dinResult.skierType})`);
    if (rec.dinResult.isJuniorAdjusted) {
      lines.push('   Junior safety adjustment applied');
    }
  }
  if (rec.xcClassicLength) {
    lines.push(`\uD83C\uDFBF XC Classic Ski Length: ${formatRange(rec.xcClassicLength.minCm, rec.xcClassicLength.maxCm)}`);
  }
  if (rec.xcSkateLength) {
    lines.push(`\uD83C\uDFBF XC Skate Ski Length: ${formatRange(rec.xcSkateLength.minCm, rec.xcSkateLength.maxCm)}`);
  }
  if (rec.alpinePoleLength != null) {
    lines.push(`\uD83D\uDCCF Alpine Poles: ${rec.alpinePoleLength} cm`);
  }
  if (rec.xcClassicPoleLength != null) {
    lines.push(`\uD83D\uDCCF XC Classic Poles: ${rec.xcClassicPoleLength} cm`);
  }
  if (rec.xcSkatePoleLength != null) {
    lines.push(`\uD83D\uDCCF XC Skate Poles: ${rec.xcSkatePoleLength} cm`);
  }

  lines.push('');
  if (rec.dinResult != null) {
    lines.push('\u26a0\ufe0f DIN settings must be verified by a certified ski technician.');
    lines.push('');
  }
  lines.push('Generated by SkiKids app');

  return lines.join('\n');
}
